[project]
name = "playground"
version = "0.1.0"
description = "playground for langextract running locally"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langextract>=1.0.6",
    "requests>=2.32.4",
]
